apiVersion: v1
kind: Service
metadata:
  name: queue-master
  labels:
    app: queue-master
  namespace: openfaas-fn
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app: queue-master
